/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package id.ac.uniska.pbo2.p03;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.FlatLaf;

/**
 *
 * @author Lenovo
 */
public class FormTiketTravel extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormTiketTravel.class.getName());

    /**
     * Creates new form FormTiketTravel
     */
    public FormTiketTravel() {
        initComponents();
        NamaField.putClientProperty("JTextField.placeholderText", "Ridho Kamaal");
        NomorField.putClientProperty("JTextField.placeholderText", "08xxxxxxxxxx");
        getRootPane().setDefaultButton(PesanButton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        KelasGroup = new javax.swing.ButtonGroup();
        NamaLabel = new javax.swing.JLabel();
        NomorHPLabel = new javax.swing.JLabel();
        KotaTujuanLabel = new javax.swing.JLabel();
        KelasLabel = new javax.swing.JLabel();
        FasilitasLabel = new javax.swing.JLabel();
        CatatanLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CatatanText = new javax.swing.JTextArea();
        NamaField = new javax.swing.JTextField();
        NomorField = new javax.swing.JTextField();
        KotaComboBox = new javax.swing.JComboBox<>();
        EkonomiRadio = new javax.swing.JRadioButton();
        BisnisRadio = new javax.swing.JRadioButton();
        EksekutifRadio = new javax.swing.JRadioButton();
        BagasiCheck = new javax.swing.JCheckBox();
        MakanCheck = new javax.swing.JCheckBox();
        AsuransiCheck = new javax.swing.JCheckBox();
        PesanButton = new javax.swing.JButton();
        temaToggle = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FormTiketTravel.form");

        NamaLabel.setText(" Nama Pemesanan");

        NomorHPLabel.setText("Nomor HP");

        KotaTujuanLabel.setText("Kota Tujuan");

        KelasLabel.setText("Kelas");

        FasilitasLabel.setText("Fasilitas Tambahan");

        CatatanLabel.setText("Catatan");

        CatatanText.setColumns(20);
        CatatanText.setRows(3);
        jScrollPane1.setViewportView(CatatanText);

        KotaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banjarbaru", "Martapura", "Palangka Raya", "Samarinda", "Balikpapan" }));

        KelasGroup.add(EkonomiRadio);
        EkonomiRadio.setSelected(true);
        EkonomiRadio.setText("Ekonomi");

        KelasGroup.add(BisnisRadio);
        BisnisRadio.setText("Bisnis");

        KelasGroup.add(EksekutifRadio);
        EksekutifRadio.setText("Eksekutif");

        BagasiCheck.setText("Bagasi");

        MakanCheck.setText("Makan");
        MakanCheck.addActionListener(this::MakanCheckActionPerformed);

        AsuransiCheck.setText("Asuransi");

        PesanButton.setText("Pesan");
        PesanButton.addActionListener(this::PesanButtonActionPerformed);

        temaToggle.setText("Mode Gelap");
        temaToggle.addActionListener(this::temaToggleActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NamaLabel)
                            .addComponent(NomorHPLabel)
                            .addComponent(KotaTujuanLabel)
                            .addComponent(KelasLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(NamaField))
                            .addComponent(NomorField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(KotaComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(EkonomiRadio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BisnisRadio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AsuransiCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EksekutifRadio))
                                .addGap(0, 83, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FasilitasLabel)
                            .addComponent(CatatanLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BagasiCheck)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MakanCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(temaToggle, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(PesanButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NamaLabel)
                    .addComponent(NamaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomorHPLabel)
                    .addComponent(NomorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(KotaTujuanLabel)
                    .addComponent(KotaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(KelasLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(EkonomiRadio)
                        .addComponent(BisnisRadio)
                        .addComponent(EksekutifRadio)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FasilitasLabel)
                    .addComponent(BagasiCheck)
                    .addComponent(MakanCheck)
                    .addComponent(AsuransiCheck))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CatatanLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PesanButton)
                    .addComponent(temaToggle))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MakanCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MakanCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MakanCheckActionPerformed

    private void PesanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesanButtonActionPerformed
       tampilkanRingkasan();
    }//GEN-LAST:event_PesanButtonActionPerformed

    private void temaToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temaToggleActionPerformed
    gantiTema(temaToggle.isSelected());
    }//GEN-LAST:event_temaToggleActionPerformed

     private void tampilkanRingkasan() {
// 1. Menentukan Kelas yang dipilih dari RadioButton
String kelas = "";
if (EkonomiRadio.isSelected()) {
    kelas = "Ekonomi";
} else if (BisnisRadio.isSelected()) {
    kelas = "Bisnis";
} else if (EksekutifRadio.isSelected()) {
    kelas = "Eksekutif";
}

// 2. Mengumpulkan Fasilitas Tambahan yang dipilih dari CheckBox
List<String> fasilitas = new ArrayList<>();
for (JCheckBox cb : List.of(BagasiCheck, MakanCheck, AsuransiCheck)) {
    if (cb.isSelected()) {
        fasilitas.add(cb.getText());
    }
}

// 3. Menyusun dan menampilkan pesan dialog
String pesan = "Nama Pemesanan: " + NamaField.getText()
        + "\nNomor HP: " + NomorField.getText()
        + "\nKota Tujuan: " + KotaComboBox.getSelectedItem()
        + "\nKelas: " + (kelas.isEmpty() ? "-" : kelas)
        + "\nFasilitas Tambahan: " + (fasilitas.isEmpty() ? "-" : String.join(", ", fasilitas))
        + "\nCatatan: " + CatatanText.getText(); 

JOptionPane.showMessageDialog(this, pesan, "Data Pemesanan Tiket", JOptionPane.INFORMATION_MESSAGE);
     }
private void gantiTema(boolean gelap) {
 if (gelap) {
FlatDarkLaf.setup();
} else {
FlatLightLaf.setup();
}
FlatLaf.updateUI(); // terapkan tema baru ke semua jendela yang terbuka
temaToggle.setText(gelap ? "Mode Terang" : "Mode Gelap");
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      FlatLightLaf.setup();
// Tampilkan form di Event Dispatch Thread
java.awt.EventQueue.invokeLater(() -> new FormPendaftaran().setVisible(true));


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormTiketTravel().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox AsuransiCheck;
    private javax.swing.JCheckBox BagasiCheck;
    private javax.swing.JRadioButton BisnisRadio;
    private javax.swing.JLabel CatatanLabel;
    private javax.swing.JTextArea CatatanText;
    private javax.swing.JRadioButton EkonomiRadio;
    private javax.swing.JRadioButton EksekutifRadio;
    private javax.swing.JLabel FasilitasLabel;
    private javax.swing.ButtonGroup KelasGroup;
    private javax.swing.JLabel KelasLabel;
    private javax.swing.JComboBox<String> KotaComboBox;
    private javax.swing.JLabel KotaTujuanLabel;
    private javax.swing.JCheckBox MakanCheck;
    private javax.swing.JTextField NamaField;
    private javax.swing.JLabel NamaLabel;
    private javax.swing.JTextField NomorField;
    private javax.swing.JLabel NomorHPLabel;
    private javax.swing.JButton PesanButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton temaToggle;
    // End of variables declaration//GEN-END:variables
}
